# Generated by Django 4.2.19 on 2025-03-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "module_id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("COMP", "Computer Science"),
                            ("MATH", "Mathematics"),
                            ("BIOL", "Biology"),
                            ("PSYC", "Psychology"),
                            ("ENGR", "Engineering"),
                            ("HIST", "History"),
                            ("ECON", "Economics"),
                            ("MEDS", "Medicine"),
                            ("PHYS", "Physics"),
                            ("LITR", "Literature"),
                        ],
                        max_length=4,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("semester", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "professor_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("rating_id", models.IntegerField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                (
                    "module_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.module",
                    ),
                ),
                (
                    "professor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.professor",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.student",
                    ),
                ),
            ],
        ),
    ]
