# Generated by Django 4.2.19 on 2025-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0002_alter_rating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="year_group",
            field=models.IntegerField(default=1),
        ),
    ]
