# Generated by Django 4.2.19 on 2025-03-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0003_module_year_group"),
    ]

    operations = [
        migrations.RemoveField(model_name="rating", name="module_id",),
        migrations.RemoveField(model_name="rating", name="professor_id",),
        migrations.CreateModel(
            name="Iteration",
            fields=[
                (
                    "iteration_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "module_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.module",
                    ),
                ),
                (
                    "professor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.professor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rating",
            name="iteration_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="professors.iteration",
            ),
            preserve_default=False,
        ),
    ]
