# Generated by Django 4.2.19 on 2025-03-16 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "professors",
            "0004_remove_rating_module_id_remove_rating_professor_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="rating", name="student_id",),
        migrations.AddField(
            model_name="rating",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Student",),
    ]
